# Project information
site_name: locdataMAC
# defeine TOC or order of website-
nav:
  - Home: index.md
  - APIreference : APIreference.md

site_author: Sachin Mishra
site_description: >-
  Python library for tracking time on each & every software as well as on website & provides the analytics.

# Repository
repo_name: SachinMishra-ux/locdataMAC
repo_url: https://github.com/SachinMishra-ux/locdataMAC

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/SachinMishra-ux
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tkwtk1
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sachin-mishra19566/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sachin19566/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/SachinMishra-ux"  target="_blank" rel="noopener">Sachin Mishra</a>